#+TITLE: Assignment 6
#+AUTHOR: Michael Hunsinger
#+OPTIONS: toc:nil
#+LATEX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LaTeX_HEADER: \usepackage{titling}
#+LaTeX_HEADER: \addtolength{\topmargin}{-0.75in}
#+LaTeX_HEADER: \addtolength{\textheight}{1.25in}
#+LaTeX_HEADER: \addtolength{\oddsidemargin}{-.75in}
#+LaTeX_HEADER: \addtolength{\evensidemargin}{-.75in}
#+LaTeX_HEADER: \addtolength{\textwidth}{1.75in}
#+LaTeX_HEADER: \usepackage{paralist}
#+LaTeX_HEADER: \setlength\parindent{0pt}
#+LaTeX_HEADER: \let\itemize\compactitem
#+LaTeX_HEADER: \let\description\compactdesc
#+LaTeX_HEADER: \let\enumerate\compactenum

* Change log
** [2014-09-08 Mon]
   - Changed the Reader from the bufio package to the bytes package. The
     bufio Reader is made to read streaming data and cannot perform seeks.
   - Changed ~compiler.go~ to a ~scanner.go~, so it is more appropriately
     named for future implementations.
   - Added a ~parser.go~ file to implement a compiler's parser functionality.
   - Added the ability to pass in the file on the command line.
** [2014-09-15 Mon]
   - Moved ~token.go~ to ~types.go~ and added support for Operator, ExprRec,
     and ExprKind.
   - Added semantic routines to the parser.
   - When running the program, the user must add a second parameter for the
     output file. For example, ~./main simple.micro generatedOutput~ will
     create a file ~generatedOutput~ with all the assembly operations generated
     during parsing.

** [2014-09-21 Sun]
   - Changed the scanner provide lexical analysis.
   - Removed the ~parser.go~ file with the new scanner implementation.
   - Added better checking for files passed in at execution.
   - Tokens are no longer their own structs, they're now an ~int~.

** [2014-09-28 Sun]
   - Implemented a grammar analyzer

** [2014-10-05 Sun]
   - This current implementation doesn't work correctly. There are issues when
     using maps for the sets. Since maps aren't read in a consistent order,
     answers will vary between executions. MarkLambda, ComputeFirst,
     FillFirstSet all work correctly, but will need to be reworked when changes
     are made. FillFollowSet does not work correctly. May have something to do
     with the maps.
** [2014-10-10 Fri]
   - There still appear to be some minor issues regarding filling the
     FollowSet, but nothing that prevents a predict set form being determined
     correctly.
* Go Documentation
This implentation of the scanner uses Google's new language Go. There are
instructions on how to setup Go, a description of the file structure, and
how to compile and run the program.

** Install Go
   Download the appropriate installation from Google's Go website,
   http://golang.org/doc/install, there is additional documentation located
   on website as well.

** Go's Workspace
   Extract files from the tarball into the desired location. Inside the root
   folder you will find four directories
   - ~bin~ compiled executables, along with sample micro program files
   - ~doc~ documentation
   - ~pkg~ package objects (the compiler package is located in here)
   - ~src~ source files
     - ~compiler~ source files pertaining to the compiler package
     - ~main~ source files pertaining to the main package (the driver file)

   We must also setup the ~GOPATH~ to ensure proper compilation of the files.
   Follow the steps below to set ~GOPATH~ in a *unix environment. 
   #+BEGIN_SRC 
   $ cd ../03
   $ export GOPATH=$HOME/your/path/here/03
   #+END_SRC
   
** Compiling Source Files
   There are two steps to compile and the executable; building the compiler
   package and then build the executable.
   #+BEGIN_SRC 
   $ cd ../03
   $ go build compiler
   $ go install main
   #+END_SRC
   Now there is an executable in the ~bin~ folder.

** Running the Program
   You can run the executable that was compiled. Ensure you are in the 
   directory where the ~simple.micro~ file is located.
   #+BEGIN_SRC 
   $ cd ../03/bin
   $ ./main simple.micro
   #+END_SRC
   This will run scan the ~simple.micro~ file. There is also a ~complex.micro~
   file in the ~bin~ folder that uses some of the tokens found in the 
   extended Micro language.

* Sample Input and Output
  The output was split up as it would not fit on one page width. The output of
  the program organizes them into column as described in the handout.

  #+BEGIN_SRC
  Input for the problem from Assignment 5, 2b
  BEGIN READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END

  Output Action
  Parser
  Predict 22
  Predict 1
  Match!
  Predict 2
  Predict 6
  Match!
  Match!
  Predict 8
  Match!
  Predict 10
  Match!
  Match!
  Predict 3
  Predict 2
  Predict 5
  Match!
  Match!
  Predict 14
  Predict 18
  Match!
  Predict 15
  Predict 20
  Match!
  Predict 14
  Predict 19
  Match!
  Predict 16
  Match!
  Predict 3
  Predict 2
  Predict 7
  Match!
  Match!
  Predict 11
  Predict 14
  Predict 18
  Match!
  Predict 16
  Predict 13
  Match!
  Match!
  Predict 4
  Match!
  Match!

  Remaining Input
  [BEGIN READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [BEGIN READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [BEGIN READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [READ ( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [( IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [IN ) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [) ; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [; OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [OUT := IN + 100 ; WRITE ( OUT ) ; END]
  [:= IN + 100 ; WRITE ( OUT ) ; END]
  [IN + 100 ; WRITE ( OUT ) ; END]
  [IN + 100 ; WRITE ( OUT ) ; END]
  [IN + 100 ; WRITE ( OUT ) ; END]
  [+ 100 ; WRITE ( OUT ) ; END]
  [+ 100 ; WRITE ( OUT ) ; END]
  [+ 100 ; WRITE ( OUT ) ; END]
  [100 ; WRITE ( OUT ) ; END]
  [100 ; WRITE ( OUT ) ; END]
  [100 ; WRITE ( OUT ) ; END]
  [; WRITE ( OUT ) ; END]
  [; WRITE ( OUT ) ; END]
  [WRITE ( OUT ) ; END]
  [WRITE ( OUT ) ; END]
  [WRITE ( OUT ) ; END]
  [WRITE ( OUT ) ; END]
  [( OUT ) ; END]
  [OUT ) ; END]
  [OUT ) ; END]
  [OUT ) ; END]
  [OUT ) ; END]
  [) ; END]
  [) ; END]
  [) ; END]
  [; END]
  [END]
  [END]
  []

  Parse Stack
  <systemgoal> 
  <program> EofSym 
  BeginSym <stmtlist> EndSym EofSym 
  <stmtlist> EndSym EofSym 
  <statement> <statementtail> EndSym EofSym 
  ReadSym LParen <idlist> RParen SemiColon <statementtail> EndSym EofSym 
  LParen <idlist> RParen SemiColon <statementtail> EndSym EofSym 
  <idlist> RParen SemiColon <statementtail> EndSym EofSym 
  Id <idtail> RParen SemiColon <statementtail> EndSym EofSym 
  <idtail> RParen SemiColon <statementtail> EndSym EofSym 
  RParen SemiColon <statementtail> EndSym EofSym 
  SemiColon <statementtail> EndSym EofSym 
  <statementtail> EndSym EofSym 
  <stmtlist> EndSym EofSym 
  <statement> <statementtail> EndSym EofSym 
  Id AssignOp <expression> SemiColon <statementtail> EndSym EofSym 
  AssignOp <expression> SemiColon <statementtail> EndSym EofSym 
  <expression> SemiColon <statementtail> EndSym EofSym 
  <primary> <primarytail> SemiColon <statementtail> EndSym EofSym 
  Id <primarytail> SemiColon <statementtail> EndSym EofSym 
  <primarytail> SemiColon <statementtail> EndSym EofSym 
  <addop> <expression> SemiColon <statementtail> EndSym EofSym 
  PlusOp <expression> SemiColon <statementtail> EndSym EofSym 
  <expression> SemiColon <statementtail> EndSym EofSym 
  <primary> <primarytail> SemiColon <statementtail> EndSym EofSym 
  IntLiteral <primarytail> SemiColon <statementtail> EndSym EofSym 
  <primarytail> SemiColon <statementtail> EndSym EofSym 
  SemiColon <statementtail> EndSym EofSym 
  <statementtail> EndSym EofSym 
  <stmtlist> EndSym EofSym 
  <statement> <statementtail> EndSym EofSym 
  WriteSym LParen <exprlist> RParen SemiColon <statementtail> EndSym EofSym 
  LParen <exprlist> RParen SemiColon <statementtail> EndSym EofSym 
  <exprlist> RParen SemiColon <statementtail> EndSym EofSym 
  <expression> <exprtail> RParen SemiColon <statementtail> EndSym EofSym 
  <primary> <primarytail> <exprtail> RParen SemiColon <statementtail> EndSym EofSym 
  Id <primarytail> <exprtail> RParen SemiColon <statementtail> EndSym EofSym 
  <primarytail> <exprtail> RParen SemiColon <statementtail> EndSym EofSym 
  <exprtail> RParen SemiColon <statementtail> EndSym EofSym 
  RParen SemiColon <statementtail> EndSym EofSym 
  SemiColon <statementtail> EndSym EofSym 
  <statementtail> EndSym EofSym 
  EndSym EofSym 
  EofSym 
  #+END_SRC
  

